name: employee_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  #state gestor
  provider: ^6.1.1
  #formatter date
  intl: ^0.19.0
  #animations
  animate_do: ^3.3.3
  #spaces
  flutter_screenutil: ^5.5.3+2
  #manager image
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

assets:
    - assets/robot.png
    - assets/local_tasks.json
    
  